// const GoogleMap({
// 	Key key,
// 	@required this.initialCameraPosition,
// 	this.onMapCreated,
// 	this.gestureRecognizers,
// 	this.compassEnabled = true,
// 	this.cameraTargetBounds = CameraTargetBounds.unbounded,
// 	this.mapType = MapType.normal,
// 	this.minMaxZoomPreference = MinMaxZoomPreference.unbounded,
// 	this.rotateGesturesEnabled = true,
// 	this.scrollGesturesEnabled = true,
// 	this.zoomGesturesEnabled = true,
// 	this.tiltGesturesEnabled = true,
// 	this.myLocationEnabled = false,
// 	this.markers,
// 	this.onCameraMoveStarted,
// 	this.onCameraMove,
// 	this.onCameraIdle,
// 	this.onTap,
// })
