# Generated by Django 3.2.5 on 2021-08-05 21:11

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataFormulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.PositiveIntegerField()),
                ('email', models.EmailField(db_index=True, max_length=200)),
                ('placa', models.CharField(blank=True, max_length=200, null=True)),
                ('marca', models.CharField(blank=True, max_length=200, null=True)),
                ('modelo', models.CharField(blank=True, max_length=200, null=True)),
                ('tipo', models.CharField(blank=True, max_length=200, null=True)),
                ('color', models.CharField(blank=True, max_length=200, null=True)),
                ('tEstimate1', models.CharField(blank=True, max_length=200, null=True)),
                ('tEstimate2', models.CharField(blank=True, max_length=200, null=True)),
                ('tEstimate3', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lugar', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.FileField(upload_to=api.models.logo_dir_path)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.dataformulario')),
            ],
        ),
    ]
